########################################################################################################################
# docker build -f Dockerfile-u20 -t u20 .
# docker run -it --privileged=true --name u20 u20
# docker run -id --privileged=true --name u20 u20
# docker exec -it u20 /bin/bash 
# docker stop u20
# docker rm   u20
# docker rmi  u20
########################################################################################################################
FROM ubuntu:20.04

LABEL Author=Steven.Zhou
LABEL Email=zhy29563@126.com
LABEL U20_Detail1="Modify apt source to tsinghua."
LABEL U20_Detail2="Update and upgrade."
LABEL U20_Detail3="Install net-tools iproute2 iputils-ping wget axel curl gawk sudo zip unzip vim xz-utils tree."
LABEL U20_Detail4="Modify the passworld of root to root."

RUN apt-get -y update                                                                                                &&\
  apt-get install -y ca-certificates                                                                                 &&\
  cp /etc/apt/sources.list /etc/apt/sources.list.bak                                                                 &&\
  sed -i "s@http://.*archive.ubuntu.com@https://mirrors.tuna.tsinghua.edu.cn@g" /etc/apt/sources.list                &&\
  sed -i "s@http://.*security.ubuntu.com@https://mirrors.tuna.tsinghua.edu.cn@g" /etc/apt/sources.list               &&\
  apt-get -y update                                                                                                  &&\
  apt-get -y upgrade                                                                                                 &&\
  apt-get -y autoremove                                                                                              &&\
  apt-get install -y net-tools iproute2 iputils-ping wget axel curl gawk sudo zip unzip vim xz-utils tree            &&\
  echo 'root:root' | chpasswd root