########################################################################################################################
# Docker Image for CMakeProjectTemplate
# docker build -f Dockerfile-runner-cpt -t runner:cpt .
# docker run -it --privileged=true --name runner_cpt runner:cpt
# docker run -id --privileged=true --name runner_cpt runner:cpt
# docker exec -it runner_cpt /bin/bash 
# docker stop runner_cpt
# docker rm   runner_cpt
# docker rmi  runner:cpt
########################################################################################################################
FROM runner:dev

LABEL Author=Steven.Zhou
LABEL Email=zhy29563@126.com
LABEL CPT_Detail1="Install xsltproc"
LABEL CPT_Detail2="Compile gtest v1.12.1 to /root/.envs/libs/x86_64-linux-gnu-v9.4.0/libgtest-1.12.1"

# 环境变量
ENV ENVS_ROOT=/root/.envs
ENV LIBS_PATH=x86_64-linux-gnu-v9.4.0
ENV LIBS_ROOT=${ENVS_ROOT}/libs/${LIBS_PATH}

RUN apt-get install -y xsltproc                                                                                      &&\
  git clone --recursive -b release-1.12.1 http://172.17.0.1:9080/root/googletest.git ${HOME}/gtest-1.12.1            &&\
  cmake -S ${HOME}/gtest-1.12.1/ -B ${HOME}/gtest-1.12.1/build/ -DCMAKE_INSTALL_PREFIX=${LIBS_ROOT}/libgtest-1.12.1  &&\
  make  -C ${HOME}/gtest-1.12.1/build -j 4                                                                           &&\
  make  -C ${HOME}/gtest-1.12.1/build install                                                                        &&\
  rm   -rf ${HOME}/gtest-1.12.1